config/routes.rb
Rails.application.routes.draw do

  root 'home#index'
  resources :requests

  get '/search' => 'requests#search'

end

app/models/request.rb
class Request < ActiveRecord::Base

  paginates_per 7

  def self.search(search)
    where('name ILIKE :name OR email ILIKE :email OR department ILIKE :department OR message ILIKE :message',
          name: "%#{search}%", email: "%#{search}%", department: "%#{search}%", message: "%#{search}%")
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController
  def new
    @request = Request.new
  end

  def create
    @request = Request.create request_params
    if @request.save
      redirect_to request_path(@request)
    else
      render :new
    end
  end

  def show
    @request = Request.find params[:id]
  end

  def index
    if params[:search]
      @requests = Request.search(params[:search]).order("created_at DESC")
    else
      @requests = Request.all.order('created_at DESC')
    end

    @requests = @requests.page(params[:page])
    # @requests = Request.all
  end

  def edit
    @request = Request.find params[:id]
  end

  def update
    request = Request.find params[:id]
    request.update request_params
    redirect_to request_path(request)
  end

  def destroy
    @request = Request.find params[:id]
    @request.destroy
    redirect_to requests_path
  end

  private
  def request_params
    params.require(:request).permit(:name,:email,:department,:message)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/views/home/index.html.erb
<h1>Company Support</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Support</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= link_to 'Home', root_path %> |
<%= link_to 'New Request', new_request_path %> |
<%= link_to 'All Requests', requests_path %> 

<%= yield %>

</body>
</html>

app/views/requests/edit.html.erb
<br>
<%= image_tag 'supporter.png' %>
<h1>Edit Form</h1>
<%= form_for @request do |f| %>
<p>
  <%= f.label :name %>
  <%= f.text_field :name %>
</p>
<p>
  <%= f.label :email %>
  <%= f.text_field :email %>
</p>
<p>
  <%= f.label :department %>:
  <%= f.label :department, 'Sales' %>
  <%= f.radio_button :department, 'Sales'%>
  <%= f.label :department, 'Marketing' %>
  <%= f.radio_button :department, 'Marketing' %>
  <%= f.label :department, 'Technical'%>
  <%= f.radio_button :department, 'Technical'%>
</p>
<p>
  <%= f.label :message %>
  <%= f.text_area :message %>
</p>
<p>
  <%= f.submit %>
</p>
<% end %>

app/views/requests/index.html.erb
<div style='float:right;'>
  <%= form_tag(requests_path, :method => "get", id: "search-form") do %>
  <%= text_field_tag :search, params[:search], placeholder: "Search Posts" %>
  <%= submit_tag "Search" %>
  <% end %>
</div>

<h1>Support Requests</h1>

<table border='1px' width='60%'>
  <tr>
    <th>Name</th>
    <th>Email</th>
    <th>Department</th>
    <th>Message</th>
    <th colspan='3'>Actions</th>
  </tr>

  <% @requests.each do |request|  %>

  <tr>
    <td><%= request.name %></td>
    <td><%= request.email %></td>
    <td><%= request.department %></td>
    <td><%= request.message %></td>
    <td align='center'><%= link_to 'Edit', edit_request_path(request) %></td>
    <td align='center'><%= link_to 'Delete', request_path(request),
    method: :delete, data: {confirm: "Are you sure?"} %></td>
    <td align='center'>

      <input type="button" value="undone" onclick="return change(this);" />

        <script type="text/javascript">
          function change( click )
          {
          if ( click.value === "undone" )
            click.value = "done";
          else
            click.value = "undone";
          }
        </script>

    </td>
  </tr>
  <% end %>
</table>

<%= paginate @requests %>

app/views/requests/new.html.erb
<br>
<%= image_tag 'supporter.png' %>
<h1>Supporter</h1>
<%= form_for @request do |f| %>
<p>
  <%= f.label :name %>
  <%= f.text_field :name %>
</p>
<p>
  <%= f.label :email %>
  <%= f.text_field :email %>
</p>
<p>
  <%= f.label :department %>:
  <%= f.label :department, 'Sales' %>
  <%= f.radio_button :department, 'Sales'%>
  <%= f.label :department, 'Marketing' %>
  <%= f.radio_button :department, 'Marketing' %>
  <%= f.label :department, 'Technical'%>
  <%= f.radio_button :department, 'Technical'%>
</p>
<p>
  <%= f.label :message %>
  <%= f.text_area :message %>
</p>
<p>
  <%= f.submit %>
</p>
<% end %>

app/views/requests/show.html.erb
<h1><%= @request.name %></h1>

<p><strong>Email</strong>:<%= @request.email %></p>

<p><strong>Department</strong>:<%= @request.department %></p>

<p><strong>Message</strong>:<%= @request.message %></p>